# Generated by Django 3.1.6 on 2021-02-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodynews', '0002_auto_20210214_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='published', max_length=10),
        ),
    ]
