# Generated by Django 3.1.6 on 2021-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodynews', '0003_auto_20210215_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='draft', max_length=10),
        ),
    ]
