# Generated by Django 3.1.6 on 2021-02-17 09:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bodynews', '0004_auto_20210215_0208'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('odjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
