# Generated by Django 3.1.6 on 2021-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodynews', '0007_auto_20210423_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка новостя'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
