# Generated by Django 3.1.6 on 2021-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodynews', '0008_auto_20210423_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts', verbose_name='Картинка новостя'),
        ),
    ]
