# Generated by Django 3.1.6 on 2021-04-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodynews', '0009_auto_20210423_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='avatar',
        ),
    ]
